# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Quick and dirty vector by sparse matrix multiplication
#' note that no bounds checking is done
#' @name multiply_sparse
#' @param mat A 3-column matrix giving the rows and columns of the non-zero entries of the 
#'     sparse matrix (columns 1 and 2) and the value (column 3)
#' @param y The vector by which to multiply mat
#' @keywords internal
NULL

#' Compute a concentration derivative for an entire river network
#' @param t the time step
#' @param y the state vector
#' @param adjacencyQ A 3-column matrix giving the rows and columns of the non-zero entries of 
#'     the adjacency matrix (columns 1 and 2) and the discharge value (column 3)
#' @param qout A vector of output discharge
#' @param qin A vector of input discharge
#' @param lateral A vector giving concentraion of lateral input
#' @param csArea Cross Sectional area of each site
#' @param dx Length of each site
dCdt_transport_cpp <- function(t, y, adjacencyQ, qout, qin, lateral, csArea, dx) {
    .Call('_WatershedTools_dCdt_transport_cpp', PACKAGE = 'WatershedTools', t, y, adjacencyQ, qout, qin, lateral, csArea, dx)
}

#' Connect points in a watershed
#' @param dsPixel A vector of downstream pixels, diPixel[i] is downstream from pixel i
connectCPP <- function(dsPixel, upstream, downstream) {
    .Call('_WatershedTools_connectCPP', PACKAGE = 'WatershedTools', dsPixel, upstream, downstream)
}

#' Construct a distance matrix between one set of points and another
#'
#' @param x  Set of pixels to which to compute distance
#' @param diPixel  A vector of downstream pixels, diPixel[i] is downstream from pixel i
#' @param nx The total number of pixels in the network
#' @param value The value to be added (e.g., length) when computing distance
#' @return A matrix with dimensions `length(x)` by `nrow(ws)`
dmat <- function(x, dsPixel, nx, value) {
    .Call('_WatershedTools_dmat', PACKAGE = 'WatershedTools', x, dsPixel, nx, value)
}

